Fix undefined reference to __fpgetprec on i386
Closes #137

This reverts commit ebcd40f1b0378522b299bfec63e288df000b43d2.

The tests were failing to load the library on i386 due to an undefined
reference to __fpgetprec, which resulted from __fpgetprec not being inlined
due to the missing definition of __GNUCLIKE_ASM and __CC_SUPPORTS___INLINE__.